# Generated by Django 3.0.2 on 2020-02-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200203_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='query',
        ),
    ]
