# Generated by Django 3.0.2 on 2020-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200204_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='urlArticle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
