# Generated by Django 3.0.2 on 2020-02-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20200204_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='login',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.AddField(
            model_name='person',
            name='lol',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
